"""empty message

Revision ID: 28349fb89a35
Revises: 71c82c80c15c
Create Date: 2022-12-08 13:43:59.306500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28349fb89a35'
down_revision = '71c82c80c15c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signature', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('signature')

    # ### end Alembic commands ###
