"""empty message

Revision ID: 71c82c80c15c
Revises: fb4ca4a16e2c
Create Date: 2022-12-08 13:43:09.420624

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '71c82c80c15c'
down_revision = 'fb4ca4a16e2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('signature')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signature', mysql.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
